# -*- coding: utf-8 -*-
"""parties_main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCIm6blVsKywjI45ivGrvbHkaTMpVj22
"""

"""
Main Script for Partisan Bias Analysis

This script ties together the preprocessing, party mention collection,
and aggregation functions to analyze partisan bias in articles.

Imports:
    - PARTY_SYNONYM_DICT, PARTIES, PUBLISHERS: configuration constants
    - main_discourse_preprocessing: preprocessing functions
    - party_mention_collect, party_count_aggregation: functions for counting and aggregating party mentions
"""

# ------------------------------
# Imports
# ------------------------------
from parties_config import PARTY_SYNONYM_DICT, PARTIES, PUBLISHERS
from parties_preprocessing import main_discourse_preprocessing
from parties_functions import party_mention_collect, party_counts_aggregation

# ------------------------------
# Function: main_parties
# ------------------------------
def main_parties(df, PARTY_SYNONYM_DICT, PARTIES, PUBLISHERS):
    """
    Main pipeline to process articles and compute party mentions.

    Parameters:
    df (pd.DataFrame): DataFrame containing at least the following columns:
        - 'content': Text of the article
        - 'date': Publication date
        - 'publisher': Publisher/source of the article

    Returns:
    tuple:
        - df_parties: DataFrame with per-article party mention counts
        - df_parties_analysis: DataFrame aggregated weekly per publisher with
          counts, totals, and percentages of party mentions

    Steps:
    1. Copy the DataFrame to avoid modifying the original.
    2. Preprocess the article text (lowercasing, removing punctuation and extra spaces).
    3. Count party mentions per article using synonyms.
    4. Aggregate party mentions weekly per publisher.
    """
    # Make a copy of the DataFrame to avoid altering original data
    df = df.copy()

    # Step 1: Preprocess text content
    df = main_discourse_preprocessing(df)

    # Step 2: Count mentions of each party in each article
    df_parties = party_mention_collect(df, PARTY_SYNONYM_DICT)

    # Step 3: Aggregate counts weekly per publisher
    df_parties_analysis = party_counts_aggregation(df_parties, PARTIES, PUBLISHERS)

    return df_parties, df_parties_analysis