# -*- coding: utf-8 -*-
"""parties_functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sildZE-AH6d1UGcdSktaJBkq5tErfZg0
"""

"""
Functions for Party Mentions Collection and Aggregation

This module contains functions to:
1. Count mentions of political parties in article texts.
2. Aggregate party mentions weekly per publisher.

Input:
    - DF_CLEAN
    - PARTY_SYNONYM_DICT: Dictionary mapping canonical party names to lists of synonyms
    - PARTIES: List of canonical party names
    - PUBLISHERS: List of publishers to include in aggregation

Output:
    - DataFrame with per-article party counts
    - Aggregated weekly DataFrame per publisher
"""

# ------------------------------
# Imports
# ------------------------------
import pandas as pd
import re

# ------------------------------
# Function: party_mention_collect
# ------------------------------
def party_mention_collect(df, party_synonym_dict):
    counts = []
    for text in df["content"]:
        if pd.isna(text):
            text = ""
        row_counts = {party: 0 for party in party_synonym_dict}  # matches parameter
        for party, synonyms in party_synonym_dict.items():
            for synonym in synonyms:
                pattern = r'(?<!\w)' + re.escape(synonym) + r'(?!\w)'
                row_counts[party] += len(re.findall(pattern, text))
        counts.append(row_counts)
    counts_df = pd.DataFrame(counts)
    df_party_counts = pd.concat([df, counts_df], axis=1)
    return df_party_counts



# ------------------------------
# Function: party_counts_aggregation
# ------------------------------
def party_counts_aggregation(df_party_counts, PARTIES, PUBLISHERS):
    """
    Aggregate party mentions weekly per publisher.

    Parameters:
    df_party_counts (pd.DataFrame): DataFrame with per-article party counts
    PARTIES (list): List of canonical party names
    PUBLISHERS (list): List of publishers to include

    Returns:
    pd.DataFrame: Aggregated weekly DataFrame with the following columns:
        - week_start: Start date of the week (Monday)
        - publisher: Publisher name
        - {party}_count: Number of articles mentioning the party at least once
        - {party}_total: Total mentions of the party in that week
        - {party}_pct: Percentage of total mentions represented by this party

    How it works:
    1. Converts the 'date' column to datetime if not already.
    2. Creates a weekly period column (weeks start on Monday).
    3. Groups data by publisher and week.
    4. For each group, computes count, total_sum, and percentage for each party.
    5. Compiles results into a DataFrame and sorts by week descending and publisher ascending.
    """
    # Ensure 'date' column is datetime
    df_party_counts["date"] = pd.to_datetime(df_party_counts["date"])

    # Rename publishers
    publishers_renaming = {
        "www.spiegel.de": "Der Spiegel",
        "www.zeit.de": "Die Zeit",
        "www.faz.net": "Die FAZ",
        "www.sueddeutsche.de": "Süddeutsche Zeitung",
        "www.bild.de": "Die Bild"
    }
    df_party_counts["publisher"] = df_party_counts["publisher"].replace(publishers_renaming)

    # Create weekly period column (weeks start on Monday)
    df_party_counts["week"] = df_party_counts["date"].dt.to_period("W-MON")

    # Group by publisher and week
    grouped = df_party_counts.groupby(["publisher", "week"])

    # Dictionary to store aggregation results
    party_counts_dict = {}

    for (publisher, week), group_df in grouped:
        # Skip publishers not in the provided list
        if publisher not in PUBLISHERS:
            continue

        party_stats = {}
        for party in PARTIES:
            # Number of articles mentioning the party at least once
            count = (group_df[party] != 0).sum()
            # Total mentions of the party
            total_sum = group_df[party].sum()
            party_stats[party] = {"count": count, "total_sum": total_sum}

        party_counts_dict[(publisher, week)] = party_stats

    # Build final DataFrame from dictionary
    rows = []
    for (publisher, week), party_stats in party_counts_dict.items():
        row = {
            "week_start": week.start_time,  # Convert Period to timestamp
            "publisher": publisher
        }

        total_mentions = 0  # Used to compute percentages

        # Add party counts and totals
        for party, stats in party_stats.items():
            row[f"{party}_count"] = stats["count"]
            row[f"{party}_total"] = stats["total_sum"]
            total_mentions += stats["total_sum"]

        # Compute percentages of total mentions
        for party, stats in party_stats.items():
            if total_mentions > 0:
                row[f"{party}_pct"] = round((stats["total_sum"] / total_mentions) * 100, 0)
            else:
                row[f"{party}_pct"] = 0

        rows.append(row)

    # Convert to DataFrame and sort
    df_aggregated = pd.DataFrame(rows)
    return df_aggregated
