# -*- coding: utf-8 -*-
"""parties_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soAv5dc4URHRpZPgtRDIXY0g-NmFbDEj
"""

"""
Preprocessing Functions for Partisan Bias Analysis

This module contains text cleaning and preprocessing functions to improve
party detection in media articles. Functions are designed to handle missing
values and standardize text before analysis.
"""

# ------------------------------
# Imports
# ------------------------------
import pandas as pd
import re
import string

# ------------------------------
# Function: lower_casing
# ------------------------------
def lower_casing(text):
    """
    Converts all text to lowercase to ensure consistent matching.

    Parameters:
    text (str or NaN): Input text to be converted.

    Returns:
    str or NaN: Lowercased text or original NaN value.

    Why: Party synonyms may appear in different capitalizations, so
    lowercasing helps with consistent detection.
    """
    if pd.isna(text):  # If the input is missing, return as is
        return text
    return text.lower()


# ------------------------------
# Function: removing_extra_spaces
# ------------------------------
def removing_extra_spaces(text):
    """
    Removes extra spaces and trims leading/trailing whitespace.

    Parameters:
    text (str or NaN): Input text to clean.

    Returns:
    str or NaN: Text with single spaces only, no leading/trailing spaces.

    Why: Extra spaces can break exact string matching for party synonyms.
    """
    if pd.isna(text):
        return text
    # Replace one or more whitespace characters with a single space and strip ends
    return re.sub(r'\s+', ' ', text).strip()


# ------------------------------
# Function: removing_punctuation
# ------------------------------
def removing_punctuation(text):
    """
    Removes all punctuation characters from the text.

    Parameters:
    text (str or NaN): Input text to clean.

    Returns:
    str or NaN: Text without punctuation.

    Why: Punctuation may appear inside or around party names (e.g., "CDU/CSU"),
    so removing it can improve matching accuracy.
    """
    if pd.isna(text):
        return text
    return text.translate(str.maketrans('', '', string.punctuation))


# ------------------------------
# Function: main_discourse_preprocessing
# ------------------------------
def main_discourse_preprocessing(df):
    """
    Applies all preprocessing steps to the 'content' column of a DataFrame.

    Steps applied:
    1. Lowercasing
    2. Removing extra spaces
    3. Removing punctuation

    Parameters:
    df (pd.DataFrame): DataFrame containing a 'content' column with text.

    Returns:
    pd.DataFrame: A new DataFrame with cleaned 'content'.

    Why: Standardizing text ensures that subsequent party detection
    works more reliably across different articles and sources.
    """
    df = df.copy()  # Avoid modifying the original DataFrame
    df["content"] = df["content"].apply(lower_casing)
    df["content"] = df["content"].apply(removing_extra_spaces)
    df["content"] = df["content"].apply(removing_punctuation)
    return df