# -*- coding: utf-8 -*-
"""parties_config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qAgOIQGpk0TZvmFkt95V15MQDARVVzj
"""

"""
Config for Partisan Bias Analysis

This configuration file defines constants used for analyzing media articles
for partisan bias. It includes:
1. PARTY_SYNONYM_DICT: mapping from canonical party names to a list of synonyms/aliases
2. PARTIES: list of all main political parties
3. PUBLISHERS: list of media publishers to include in analysis
"""

# ------------------------------
# Dictionary of party synonyms
# ------------------------------
# Keys are canonical party names.
# Values are lists of alternative names, nicknames, abbreviations, or misspellings
# that might appear in articles.
PARTY_SYNONYM_DICT = {
    "CDU/CSU": [
        # CDU synonyms
        "cdu", "christdemokraten", "christliche demokraten", "union", "schwarze",
        "c d u", "zdu", "cedu", "christdemokratinnen", "christliche demokratinnen",
        "christdemokratische partei",
        # CSU synonyms
        "csu", "christsoziale", "christlich-soziale", "bayerische union", "christsozialen",
        "c s u", "cesu", "zesu", "christsozialinnen"
    ],
    "SPD": [
        # SPD synonyms
        "spd", "sozialdemokraten", "sozis", "rote", "arbeiterpartei", "genossen",
        "sp d", "esspeedee", "spdee", "sozialdemokratinnen", "genossinnen",
        "sozialdemokratische partei"
    ],
    "Grüne": [
        # Green Party synonyms
        "grünen", "bündnis 90/die grünen", "ökos", "umweltpartei", "klimapartei",
        "grün-alternative partei", "grüne", "gruenen", "gruene", "grüninnen",
        "bündis 90", "bundnis 90", "grüne partei"
    ],
    "FDP": [
        # FDP synonyms
        "fdp", "liberale", "gelbe", "freidemokraten", "liberalen", "marktliberale",
        "frei demokratische partei", "f d p", "fd pee", "efdeepee", "gelben", "liberallinnen"
    ],
    "AfD": [
        # AfD synonyms
        "afd", "alternative", "rechtspopulisten", "blaue", "rechtspartei",
        "nationalkonservative", "blauen", "a f d", "af de", "aphd", "altantive",
        "alternative für deutschland", "rechtspopulistinnen", "rechtspopulistische partei"
    ],
    "Die Linke": [
        # The Left Party synonyms
        "d linke", "dee linke", "d lünke", "dee lünke", "die linke", "linkspartei", "sozialisten"
    ]
}

# ------------------------------
# List of canonical party names
# ------------------------------
# This is useful for iterating over parties or indexing results.
PARTIES = ["CDU/CSU", "SPD", "Grüne", "FDP", "AfD", "Die Linke"]

# ------------------------------
# List of media publishers
# ------------------------------

PUBLISHERS = ["Der Spiegel", "Die Zeit", "Die FAZ", "Süddeutsche Zeitung", "Die Bild"]
