# -*- coding: utf-8 -*-
"""crawling_config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIJQCz6ouLQgSsLUbS7iIZg8UMQI0aNB

### Configuration file for crawling.
- Seeding URLS, regex patterns and CSS Selectors.
"""

# src/configs/crawling_config.py
import re

# List of seed URLs (entry points for scraping)
SEEDING_URLS = [
    "https://www.zeit.de/index",
    "https://www.faz.net/aktuell/",
    "https://www.sueddeutsche.de/",
    "https://taz.de/",
    "https://www.welt.de/",
    "https://www.bild.de/",
    "https://www.spiegel.de/"
]

# Rules to identify article URLs per domain

ARTICLE_IDENTIFIERS = {
    "www.zeit.de": re.compile(r"/\d{4}-\d{2}/"),         # matches /YYYY-MM/ pattern
    # Also includes podcasts so far - to cut after?
    "www.faz.net": re.compile(r"\d{9}\.html$"),          # matches 9 digits + .html
    "www.sueddeutsche.de": re.compile(
        r"(?:/artikel|li\.\d{7}$|e\.\d{6}$)"             # matches /artikel OR li.####### OR e.######
    ),
    "www.taz.de": re.compile(r"!\d{7}/$"),                   # matches !#######/ at the end
    "www.welt.de": re.compile(
        r"/article", re.IGNORECASE                       # matches any URL containing /article
        # NOTE: does NOT include Plus articles (e.g. paid content).
    ),
    "www.bild.de": re.compile(
        r"(?:/politik|/news)", re.IGNORECASE             # matches URLs containing /politik OR /news
    ),
    "www.spiegel.de": re.compile(
        r"-a-", re.IGNORECASE                            # matches any URL containing -a-
    )
}


# CSS selectors to extract article content
# Only scrapes first page for all
# As List:

# CSS selectors to extract article content (list-based)
SELECTORS = {
    "www.faz.net": {
        "paragraphs": ['p[data-selector="body-paragraph"]', 'div[data-selector="body-text"]'],
        "date": ['time[datetime]', 'span[class*="date"]'],
        "title": ['div[data-external-selector="header-title"]', 'h1[class*="headline"]']
    },
    "www.sueddeutsche.de": {
        "paragraphs": ['p[data-manual="paragraph"]', 'div[class*="article-body"] p'],
        "date": ['time[data-manual="date"]', 'span[class*="date"]'],
        "title": ['span[data-manual="title"]', 'h1[class*="headline"]']
    },
    "www.zeit.de": {
        "paragraphs": ['p.paragraph.article__item', 'div[class*="article-body"] p'],
        "date": ['.metadata__date', 'span[class*="date"]'],
        "title": ['.article-heading__title', 'h1[class*="headline"]']
    },
    "www.taz.de": {
        "paragraphs": ['p.bodytext.paragraph', 'div[class*="article-body"] p'],
        "date": ['time.typo-meta-data', 'span[class*="date"]'],
        "title": ['span.headline.typo-r-head-detail', 'h1[class*="headline"]']
    },
    "www.welt.de": {
        "paragraphs": [
            "p[data-external='Article.FirstParagraph']",
            "div.c-rich-text-renderer--article p",
            "article p",
            'div[class*="article-body"] p'
        ],
        "date": ['span.c-article-header__date', 'span[class*="date"]'],
        "title": ['h1.c-article-header__headline', 'h2[class*="headline"]']
    },
    "www.bild.de": {
        "paragraphs": ['p', 'div[class*="article-body"] p'],
        "date": ['time.datetime--article', 'span[class*="date"]'],
        "title": ['span.headline', 'h1[class*="headline"]']
    },
    "www.spiegel.de": {
        "paragraphs": ['div[data-sara-click-el="body_element"] p', 'div[class*="article-body"] p'],
        "date": ['time.timeformat', 'span[class*="date"]'],
        "title": ['h2 span.font-extrabold', 'h1[class*="headline"]']
    }
}