# -*- coding: utf-8 -*-
"""total_config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_BhrgxOx-k9lMDdktyvR-O57IuaeUBh
"""

# paths

RAW_DATA_PATH = "/content/drive/MyDrive/Media Monitoring/Data/Final/RAW_DATA.csv"
CLEAN_DATA_PATH = "/content/drive/MyDrive/Media Monitoring/Data/Final/CLEAN_DATA.csv"
EMBEDDINGS_DATA_PATH = "/content/drive/MyDrive/Media Monitoring/Data/Final/EMBEDDINGS_DATA.parquet"
TOPICS_DATA_PATH = "/content/drive/MyDrive/Media Monitoring/Data/Final/TOPICS_DATA.parquet"
PARTIES_DATA_PATH = "/content/drive/MyDrive/Media Monitoring/Data/Final/PARTIES_DATA.csv"
PARTIES_ANALYSIS_PATH = "/content/drive/MyDrive/Media Monitoring/Data/Final/PARTIES_ANALYSIS.csv"